<?php

// This file is generated by Composer
require_once '../vendor/autoload.php';

use \Databox\DataboxClient;
use \Databox\DataboxException;
use \Databox\DataboxBuilder;
use \Guzzle\Common\Exception\RuntimeException;
use \Exception;

// api_key is required, but if you intend to push to only one custom connection, you can add uniqueUrl aswell.

$client = DataboxClient::factory([
    'apiKey' => "1234321"
]);

//Instantiate the builder
$builder = new DataboxBuilder();

//The addKpi method uses the accepts $key, $value, $date (in that order). Date should be a timestamp in the format Y-m-d\TH:i:s. Date may be NULL, in which case the current UTC time will be used.
$builder->addKpi("myKey", 123);
$builder->addKpi("myExtraKey", 300, "2013-07-30T22:53:00");

//You must provide uniqueURL and payload parameters. Payload can be any JSON string, but we reccommend you use our builder class.
try {
    $client->setPushData([
        'uniqueUrl' => 'leURL125',
        'payload'   => $builder->getPayload()
    ]);
} catch (DataboxException $e) {
    echo $e->getType();
    echo $e->getWebMessage();
    echo $e->getMessage();
} catch (RuntimeException $e) {
    echo $e->getMessage();
    echo $e->getCode();
} catch (Exception $e) {
    echo $e->getMessage();
} 

//You can reset the builder and reuse the same instance for pushing to a different custom app, if you want to.
$builder->reset();
$builder->addKpi("mySecondAppKey", 123);
$builder->addKpi("mySecondAppExtraKey", 300, "2013-07-30T22:53:00");
